const defaultStudents = [
  {
    stdRegNumber: 'BCS221068',
    firstName: 'Ali',
    lastName: 'Khan',
    fatherName: 'Ahmed Khan',
    fatherOccupation: 'Engineer',
    dateOfBirth: '2002-01-10',
    section: '1',
    email: 'ali.khan@example.com',
    contactNumber: '03001234567',
    gender: 'M',
    cnic: '12345-6789012-3',
    semester: '3',
    department: 'CS',
    program: 'BCS',
    address: {
      houseNo: '10',
      street: 'A',
      town: 'G-10',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BBA221001',
    firstName: 'Sara',
    lastName: 'Ahmed',
    fatherName: 'Faisal Ahmed',
    fatherOccupation: 'Businessman',
    dateOfBirth: '2001-05-15',
    section: '2',
    email: 'sara.ahmed@example.com',
    contactNumber: '03011234567',
    gender: 'F',
    cnic: '12345-6789013-4',
    semester: '4',
    department: 'BA',
    program: 'BBA',
    address: {
      houseNo: '22',
      street: 'B',
      town: 'F-8',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BEE221002',
    firstName: 'Usman',
    lastName: 'Tariq',
    fatherName: 'Tariq Mehmood',
    fatherOccupation: 'Teacher',
    dateOfBirth: '2001-09-25',
    section: '1',
    email: 'usman.tariq@example.com',
    contactNumber: '03021234567',
    gender: 'M',
    cnic: '12345-6789014-5',
    semester: '2',
    department: 'EE',
    program: 'BEE',
    address: {
      houseNo: '15',
      street: 'C',
      town: 'DHA',
      city: 'Lahore',
    },
  },
  {
    stdRegNumber: 'BSE221003',
    firstName: 'Zara',
    lastName: 'Hussain',
    fatherName: 'Imran Hussain',
    fatherOccupation: 'Doctor',
    dateOfBirth: '2002-02-11',
    section: '3',
    email: 'zara.hussain@example.com',
    contactNumber: '03031234567',
    gender: 'F',
    cnic: '12345-6789015-6',
    semester: '5',
    department: 'SE',
    program: 'BSE',
    address: {
      houseNo: '18',
      street: 'D',
      town: 'Model Town',
      city: 'Lahore',
    },
  },
  {
    stdRegNumber: 'BME221004',
    firstName: 'Bilal',
    lastName: 'Hassan',
    fatherName: 'Hassan Ali',
    fatherOccupation: 'Architect',
    dateOfBirth: '2000-07-19',
    section: '2',
    email: 'bilal.hassan@example.com',
    contactNumber: '03041234567',
    gender: 'M',
    cnic: '12345-6789016-7',
    semester: '6',
    department: 'ME',
    program: 'BME',
    address: {
      houseNo: '20',
      street: 'E',
      town: 'F-11',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BCS221005',
    firstName: 'Ayesha',
    lastName: 'Farooq',
    fatherName: 'Farooq Sheikh',
    fatherOccupation: 'Lawyer',
    dateOfBirth: '2001-08-30',
    section: '1',
    email: 'ayesha.farooq@example.com',
    contactNumber: '03051234567',
    gender: 'F',
    cnic: '12345-6789017-8',
    semester: '4',
    department: 'CS',
    program: 'BCS',
    address: {
      houseNo: '25',
      street: 'F',
      town: 'Johar Town',
      city: 'Lahore',
    },
  },
  {
    stdRegNumber: 'BCE221006',
    firstName: 'Hamza',
    lastName: 'Malik',
    fatherName: 'Malik Shahid',
    fatherOccupation: 'Civil Engineer',
    dateOfBirth: '2001-12-12',
    section: '2',
    email: 'hamza.malik@example.com',
    contactNumber: '03061234567',
    gender: 'M',
    cnic: '12345-6789018-9',
    semester: '3',
    department: 'CE',
    program: 'BCE',
    address: {
      houseNo: '30',
      street: 'G',
      town: 'I-8',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BSE221007',
    firstName: 'Rida',
    lastName: 'Iqbal',
    fatherName: 'Iqbal Ahmed',
    fatherOccupation: 'Software Engineer',
    dateOfBirth: '2002-04-14',
    section: '3',
    email: 'rida.iqbal@example.com',
    contactNumber: '03071234567',
    gender: 'F',
    cnic: '12345-6789019-0',
    semester: '5',
    department: 'SE',
    program: 'BSE',
    address: {
      houseNo: '35',
      street: 'H',
      town: 'Bahria Town',
      city: 'Karachi',
    },
  },
  {
    stdRegNumber: 'BCS221008',
    firstName: 'Hassan',
    lastName: 'Ali',
    fatherName: 'Ali Raza',
    fatherOccupation: 'Banker',
    dateOfBirth: '2002-06-20',
    section: '2',
    email: 'hassan.ali@example.com',
    contactNumber: '03081234567',
    gender: 'M',
    cnic: '12345-6789020-1',
    semester: '4',
    department: 'CS',
    program: 'BCS',
    address: {
      houseNo: '40',
      street: 'I',
      town: 'Clifton',
      city: 'Karachi',
    },
  },
  {
    stdRegNumber: 'BBA221009',
    firstName: 'Fahad',
    lastName: 'Sheikh',
    fatherName: 'Sheikh Asif',
    fatherOccupation: 'Businessman',
    dateOfBirth: '2002-09-22',
    section: '1',
    email: 'fahad.sheikh@example.com',
    contactNumber: '03091234567',
    gender: 'M',
    cnic: '12345-6789021-2',
    semester: '3',
    department: 'BA',
    program: 'BBA',
    address: {
      houseNo: '45',
      street: 'J',
      town: 'Gulshan-e-Iqbal',
      city: 'Karachi',
    },
  },
  {
    stdRegNumber: 'BEE221010',
    firstName: 'Imran',
    lastName: 'Haider',
    fatherName: 'Haider Ali',
    fatherOccupation: 'Electrician',
    dateOfBirth: '2002-01-25',
    section: '2',
    email: 'imran.haider@example.com',
    contactNumber: '03101234567',
    gender: 'M',
    cnic: '12345-6789022-3',
    semester: '3',
    department: 'EE',
    program: 'BEE',
    address: {
      houseNo: '50',
      street: 'K',
      town: 'G-9',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BME221011',
    firstName: 'Saad',
    lastName: 'Khan',
    fatherName: 'Javed Khan',
    fatherOccupation: 'Mechanical Engineer',
    dateOfBirth: '2001-10-18',
    section: '1',
    email: 'saad.khan@example.com',
    contactNumber: '03111234567',
    gender: 'M',
    cnic: '12345-6789023-4',
    semester: '5',
    department: 'ME',
    program: 'BME',
    address: {
      houseNo: '55',
      street: 'L',
      town: 'DHA',
      city: 'Lahore',
    },
  },
  {
    stdRegNumber: 'BCS221012',
    firstName: 'Areeba',
    lastName: 'Zafar',
    fatherName: 'Zafar Iqbal',
    fatherOccupation: 'IT Manager',
    dateOfBirth: '2002-07-07',
    section: '2',
    email: 'areeba.zafar@example.com',
    contactNumber: '03121234567',
    gender: 'F',
    cnic: '12345-6789024-5',
    semester: '3',
    department: 'CS',
    program: 'BCS',
    address: {
      houseNo: '60',
      street: 'M',
      town: 'Gulberg',
      city: 'Lahore',
    },
  },
  {
    stdRegNumber: 'BSE221013',
    firstName: 'Umar',
    lastName: 'Farooq',
    fatherName: 'Farooq Ahmed',
    fatherOccupation: 'Software Developer',
    dateOfBirth: '2001-08-05',
    section: '1',
    email: 'umar.farooq@example.com',
    contactNumber: '03131234567',
    gender: 'M',
    cnic: '12345-6789025-6',
    semester: '4',
    department: 'CS',
    program: 'BSE',
    address: {
      houseNo: '65',
      street: 'N',
      town: 'F-6',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BCE221014',
    firstName: 'Maria',
    lastName: 'Iqbal',
    fatherName: 'Iqbal Raza',
    fatherOccupation: 'Civil Engineer',
    dateOfBirth: '2000-09-12',
    section: '3',
    email: 'maria.iqbal@example.com',
    contactNumber: '03141234567',
    gender: 'F',
    cnic: '12345-6789026-7',
    semester: '6',
    department: 'CE',
    program: 'BCE',
    address: {
      houseNo: '70',
      street: 'O',
      town: 'G-11',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BBA221015',
    firstName: 'Zain',
    lastName: 'Malik',
    fatherName: 'Malik Akbar',
    fatherOccupation: 'Businessman',
    dateOfBirth: '2001-06-25',
    section: '2',
    email: 'zain.malik@example.com',
    contactNumber: '03151234567',
    gender: 'M',
    cnic: '12345-6789027-8',
    semester: '4',
    department: 'BA',
    program: 'BBA',
    address: {
      houseNo: '75',
      street: 'P',
      town: 'Johar Town',
      city: 'Lahore',
    },
  },
  {
    stdRegNumber: 'BME221016',
    firstName: 'Fatima',
    lastName: 'Rasheed',
    fatherName: 'Rasheed Ahmed',
    fatherOccupation: 'Mechanical Engineer',
    dateOfBirth: '2002-02-02',
    section: '3',
    email: 'fatima.rasheed@example.com',
    contactNumber: '03161234567',
    gender: 'F',
    cnic: '12345-6789028-9',
    semester: '2',
    department: 'ME',
    program: 'BME',
    address: {
      houseNo: '80',
      street: 'Q',
      town: 'F-10',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BCS221017',
    firstName: 'Yasir',
    lastName: 'Shah',
    fatherName: 'Shahbaz Khan',
    fatherOccupation: 'Banker',
    dateOfBirth: '2002-12-12',
    section: '1',
    email: 'yasir.shah@example.com',
    contactNumber: '03171234567',
    gender: 'M',
    cnic: '12345-6789029-0',
    semester: '3',
    department: 'CS',
    program: 'BCS',
    address: {
      houseNo: '85',
      street: 'R',
      town: 'F-7',
      city: 'Islamabad',
    },
  },
  {
    stdRegNumber: 'BEE221018',
    firstName: 'Kamran',
    lastName: 'Abbasi',
    fatherName: 'Abbasi Iqbal',
    fatherOccupation: 'Engineer',
    dateOfBirth: '2001-11-11',
    section: '2',
    email: 'kamran.abbasi@example.com',
    contactNumber: '03181234567',
    gender: 'M',
    cnic: '12345-6789030-1',
    semester: '5',
    department: 'EE',
    program: 'BEE',
    address: {
      houseNo: '90',
      street: 'S',
      town: 'Bahria Town',
      city: 'Karachi',
    },
  },
  {
    stdRegNumber: 'BSE221019',
    firstName: 'Sana',
    lastName: 'Malik',
    fatherName: 'Malik Ahmed',
    fatherOccupation: 'Doctor',
    dateOfBirth: '2002-03-03',
    section: '1',
    email: 'sana.malik@example.com',
    contactNumber: '03191234567',
    gender: 'F',
    cnic: '12345-6789031-2',
    semester: '3',
    department: 'CS',
    program: 'BSE',
    address: {
      houseNo: '95',
      street: 'T',
      town: 'Clifton',
      city: 'Karachi',
    },
  },
];

export default defaultStudents;

/* [
  'BCS221093', 'BCS221068', 'BBA221001', 'BEE221002', 'BSE221003', 
  'BME221004', 'BCS221005', 'BCE221006', 'BSE221007', 'BCS221008', 
  'BBA221009', 'BEE221010', 'BME221011', 'BCS221012', 'BSE221013', 
  'BCE221014', 'BBA221015', 'BME221016', 'BCS221017', 'BEE221018', 
  'BCS221057', 'BCS221050'
] */
